name: Linkchecker Releaser

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o linkchecker ./cmd/linkchecker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o linkchecker.exe ./cmd/linkchecker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get previous release
        id: prev_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release for Linux
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: ./linkchecker
          prerelease: false
          body: "Release for Linux"
          tag_name: v${{ steps.prev_release.outputs.next_version }}
          release_name: Release ${{ steps.prev_release.outputs.next_version }} for Linux

      - name: Create Release for Windows
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: ./linkchecker.exe
          prerelease: false
          body: "Release for Windows"
          tag_name: v${{ steps.prev_release.outputs.next_version }}
          release_name: Release ${{ steps.prev_release.outputs.next_version }} for Windows
